### ISSUE TITLE
ingress-http-domain is not a domain

### ISSUE THREAD

**Issue by ChevronTango** [exposr/exposr-server#12]
`--ingress-http-domain http://localhost:8080` is not a domain, its a fully qualified url, which makes it very confusing when this is broken down later and subdomains added. This should be broken down clearly into `scheme`, `domain` and `port` to make it clear to users how the various settings are being used. We should also consider if "ingress" is the clearest terminology for what this setting is providing.

As an aside, this should also be the domain returned in the websocket url field, rather than being pulled from the incoming host name.

**Comment by fredriklindberg** [comment]
The option is called `ingress-http-url` since 0.8.0 (#24). (ingress-http-domain still works).
