### ISSUE TITLE
Multiple Clients for Horizontal Scaling

### ISSUE THREAD

**Issue by ChevronTango** [exposr/exposr-server#9]
The current model works well for single clients and server models, however, a lot of systems, particularly those with high traffic volumes would want to scale out horizontally if traffic loads get high. Can Exposr support either the server or the clients scaling out when under load or would those all need to be unique clients with unique tunnel names?

**Comment by fredriklindberg** [comment]
The server has already horizontally scalable to support multiple (different) clients.
With version 0.8.1, each client will establish multiple (default 2) connections to the server,
traffic is load balanced round-robin over established connections. (Requires version 0.8.0 of the client).

The max number of connections per client (tunnel) can be set with starting the server.
